rails/solid_cache

- Gemfile.lock
- README.md
👋 
I saw this new gem pop up and thought I'd look under the hood. 
When following the Development steps, the tests wouldn't run without first creating the test databases within MySQL/PostgreSQL, and running the initial migrations. 
I have updated the docs to suggest they run `db:setup` after running docker-compose.
> Update testing documentation

- Gemfile
- Gemfile.lock
“pg” is the proper gem to use. “postgresql” is just to help when they get the name wrong.
> Use pg gem instead of postgresql

- .github/workflows/main.yml
It would be wonderful to see, if change in OR fails with all versions of DB or just one. Fail fast setting unfortunately stops when it encounters first failure.
> CI: don't fail fast

- app/models/solid_cache/entry.rb
The method SolidCache::Entry.expire is defined twice on that class.
The one that is actually used by the gem is defined in the lines 67-71:
https://github.com/rails/solid_cache/blob/e4865809025d650736d818fce26d09737f6623b1/app/models/solid_cache/entry.rb#L67-L71
> Remove unused redefined method SolidCache::Entry.expire(ids)

- bin/release
- gemfiles/rails_7.gemfile.lock
- gemfiles/rails_7_1.gemfile.lock
- gemfiles/rails_main.gemfile.lock
Update gemfiles for v0.2.0 and ensure they are updated in future releases.
> V0.2.0 gemfiles

- lib/solid_cache/cluster.rb
I know it is cosmetic change, but it is so uncommon in Ruby to start with empty line (at least to me) I couldn't resist to open PR to fix this file.
> Remove leading new-line in cluster.rb

- app/models/solid_cache/entry.rb
put the right default binds value as in https://github.com/rails/rails/blob/bf725a787609cf24ae64d763636513fc0bfdd4bf/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb#L100
otherwise, I have that following error 
```
NoMethodError:
undefined method `map' for nil:NilClass
```
> fix empty binds

- app/models/solid_cache/record.rb
- lib/solid_cache.rb
- test/unit/solid_cache_test.rb
Don't let the ActiveRecord::Base role bleed into the SolidCache connections. This is a problem when the default role is :reading and the SolidCache connection does not have a value set.
> Use the default SolidCache::Record role

- README.md
- app/models/solid_cache/entry.rb
- test/unit/expiry_test.rb
Right now, Solid Cache will accept a config with `max_age: nil` but will throw a `NoMethodError` when attempting to expire entries with that config. Such a config should be handled or disallowed.
Since `max_entries: nil` is allowed, this PR allows a nil value for `max_age` as well.
> Handle max_age: nil

- app/models/solid_cache/entry.rb
- lib/solid_cache/store/api.rb
- lib/solid_cache/store/entries.rb
I noticed that the `delete_multi` method is slow and makes n queries - It would be faster to delete multiple records with a single query.
> Improve performance of delete_multi method

- README.md
- lib/solid_cache/cluster/expiry.rb
- test/unit/expiry_test.rb
Add `expiry_queue` to the cache config. It can be used to specify a custom queue for SolidCache::ExpiryJob.
Resolves https://github.com/rails/solid_cache/issues/113
> Expire records on a custom queue

- app/models/solid_cache/entry.rb
- lib/solid_cache/store/api.rb
- lib/solid_cache/store/entries.rb
- test/unit/cluster_test.rb
- test/unit/delete_matched_test.rb
- test/unit/query_cache_test.rb
`delete_matched` is optional, it may be removed in Rails 8.0 and relies on the index on the `key` column which will be removed in future.
> Remove support for delete_matched

- .github/workflows/main.yml
- Gemfile.lock
- README.md
- gemfiles/rails_7.gemfile.lock
- gemfiles/rails_7_1.gemfile.lock
- gemfiles/rails_main.gemfile.lock
👋 Thanks for the review in advance.
- Adds Rails supported Ruby versions including 3.3 in the CI matrix.
- It also updates the appraisals to update Nokogiri as on Ruby 3.3
the current version on *.lock files was failing as below:
```
nokogiri-1.15.4-x86_64-linux requires ruby version < 3.3.dev, >= 2.7, which is
incompatible with the current version, 3.3.0
```
> Add Rails supported Ruby versions on CI and update appraisals

- lib/solid_cache/cluster/expiry.rb
- test/unit/expiry_test.rb
If the lifespan of a process is smaller than an expiry cycle then it may not trigger the expiry process often enough. We mitigate this a little bit by pre-filling the counter with a random number, but that means that on average a process still needs to survive for half an expiry cycle.
Instead lets trigger expiry randomly, but keep the same overall frequency. This will always give us an expiry rate proportional to the number of writes whatever the process length.
Fixes #91
> Replace expiry counter with random chance

- lib/solid_cache/cluster/execution.rb
- test/test_helper.rb
- test/unit/cluster_test.rb
- test/unit/execution_test.rb
- test/unit/expiry_test.rb
Wait for background tasks rather hope they'll be done in 0.1 seconds
> Fix flakey test

- lib/solid_cache/cluster/expiry.rb
- test/unit/expiry_test.rb
Expiries should be proportional to the number of items written, not the number of write operations.
We multiply the number of writes by the expiry chance to determine how many expiries to trigger. We trigger an expiry for every whole number in that muliplied value and determine whether to trigger an extra expiry based on the remainder.
> Expire more for larger writes

- app/models/solid_cache/entry.rb
- db/migrate/20240108155507_add_key_hash_and_byte_size_to_solid_cache_entries.rb
- db/migrate/20240110111600_add_key_hash_and_byte_size_indexes_and_null_constraints_to_solid_cache_entries.rb
- db/migrate/20240110111702_remove_key_index_from_solid_cache_entries.rb
- lib/solid_cache.rb
- lib/solid_cache/engine.rb
- test/dummy/db/primary_shard_one_schema.rb
- test/dummy/db/primary_shard_two_schema.rb
- test/dummy/db/schema.rb
- test/dummy/db/secondary_shard_one_schema.rb
- test/dummy/db/secondary_shard_two_schema.rb
- test/models/solid_cache/entry_test.rb
- upgrading_to_version_0.4.x.md
This adds a key_hash column to the solid_cache_entries table. This column is a 64-bit integer that is a truncated SHA256 hash of the key. This allows us to use a smaller index than the 1024 byte key column.
The byte_size column is also added to the table. This is the size of the value in bytes. This is for a separate feature but is included in this commit to piggy back on the migrations.
The migrations themselves are split into three steps. This allows existing tables to be migrated without downtime.
There is a new configuration field `key_hash_stage` that can be set to `:ignored`, `:unindexed` or `:indexed`. This controls how the key_hash column is used and should be set as the migrations are completed.
The default is :indexed, which is what is required for fresh installations of …
> Add key_hash for smaller index

- app/models/solid_cache/entry.rb
Check for whether the key_hash column exists in case of upgrades to the new version without setting `SolidCache.key_hash_stage == :ignored`.
> Failsafe no key_hash_stage

- db/migrate/20240110111702_remove_key_index_from_solid_cache_entries.rb
Currently, the `RemoveKeyIndexFromSolidCacheEntries` migration isn't reversible because `unique: true` is missing from `remove_index`.
> Fix RemoveKeyIndexFromSolidCacheEntries migration

- upgrading_to_version_0.4.x.md
PR adds in the commands required to copy over the new migration files, as well as the commands to run a single migration into the v0.4.x migration guide.
> Add more specific instructions for upgrading

- app/models/solid_cache/entry.rb
- lib/solid_cache/engine.rb
The option now does nothing. We assume that the key_hash column is present and indexed
> Deprecate key_hash_stage

- README.md
- app/jobs/solid_cache/expiry_job.rb
- app/models/solid_cache/entry.rb
- app/models/solid_cache/entry/expiration.rb
- app/models/solid_cache/entry/size.rb
- lib/solid_cache/cluster/expiry.rb
- lib/solid_cache/configuration.rb
- lib/solid_cache/engine.rb
- test/models/solid_cache/entry/size_test.rb
- test/unit/expiry_test.rb
- test/unit/solid_cache_test.rb
Add a new option to the cache to limit it by size. The size is estimated by sampling the `byte_size` column of the cache entries.
The size estimation firsts loads the `byte_size` of the N largest records ("the outliers"). We also grab the smallest size in that list to use as a cutoff for estimating the size of the remaining records ("the non-outliers").
The estimate of the size of the non-outliers is calculated by sampling a random portion of the records. To quickly sample the records we use the index on `key_hash` and `byte_size`.
We estimate how many records we'll need to sample by dividing the sample size by the estimated record count. This is our sample fraction.
We choose a random range of `key_hash` values the size of our sample fraction. We then sum the `byte_size` of the records …
> Expire the cache by size

- lib/solid_cache/engine.rb
- test/dummy/config/environments/test.rb
- test/unit/rails_cache_test.rb
Ensure that we have loaded solid_cache.yml before the cache store is initialized.
> Load config before cache initialization

- README.md
Pretty sure this is supposed to be `&development`, not `&production`.
> Fix typo in README config example

- README.md
Hi team! 
I just fixed the Cache Configuration link in README because it was written incorrectly.
(Existing links do not point to cache configuration section properly)
> Fix for incorrect link

- app/models/solid_cache/entry/size.rb
- app/models/solid_cache/entry/size/estimate.rb
- app/models/solid_cache/entry/size/moving_average_estimate.rb
- test/models/solid_cache/entry/size/estimate_test.rb
- test/models/solid_cache/entry/size/moving_average_estimate_test.rb
- test/models/solid_cache/entry/size_test.rb
- test/unit/expiry_test.rb
With small caches, the outlier query is very effective at reducing the
error bars on the cache size estimate. As the cache grows though, it
becomes a small % of the total cache size.
Since the entry sizes can have a long tail, the small number of large
entries in the sample query can have a big effect on the overall
estimate.
To counteract this, we'll use a moving average of the last N estimates.
The estimates will be stored directly in the cache so can be shared
amongst all processes.
We'll calculate N such that we'll try to have sampled at least 0.05% of
all records in the cache, with a maximum of 50 estimates. Testing shows
this should roughly keep us within a +/-5% error margin.
There's a race condition on writing the moving average back, but that
should be rare and not important.
If …
> Use a moving average of cache size estimates

- README.md
- lib/solid_cache/cluster/expiry.rb
- test/unit/expiry_test.rb
This allows us to trim the cache more aggresively for when we want to reduce the cache size.
> Set the expiry multiplier to 2

- app/models/solid_cache/entry.rb
- docker-compose.yml
- test/dummy/config/environments/development.rb
- test/models/solid_cache/entry/size/estimate_test.rb
- test/models/solid_cache/entry/size/moving_average_estimate_test.rb
- test/models/solid_cache/entry/size_test.rb
- test/models/solid_cache/entry_test.rb
Some experimentation suggests the row overhead for MySQL and Postgresql is 130-150 bytes beyond the size of the key and value columns.
On Sqlite it is more like 90 bytes though, but let's go for the worst case.
> More realistic row overhead estimate

- lib/active_support/cache/solid_cache_store.rb
In case we have `gem "solid_cache", require "false"` in our Gemfile.
> Require solid_cache in the store

- db/migrate/20240108155507_add_key_hash_and_byte_size_to_solid_cache_entries.rb
- db/migrate/20240110111600_add_key_hash_and_byte_size_indexes_and_null_constraints_to_solid_cache_entries.rb
- db/migrate/20240110111702_remove_key_index_from_solid_cache_entries.rb
This PR ensures that migrations won't fail when running in a Rails 7.0 application.
> Update migrations to be compatible with Rails >= 7

- README.md
This PR fixes punctuation and grammar errors in the README file.
> Fix punctuation and typo in README

- README.md
- app/models/solid_cache/entry.rb
- app/models/solid_cache/entry/size/estimate.rb
- app/models/solid_cache/entry/size/moving_average_estimate.rb
Makes the following documentation updates:
- Typo fixes
- Minor grammatical updates
- Ends ordered lists with punctuation for consistency
- Removes ending punctuation from unordered lists for consistency
> Fix documentation typos and grammar

- app/models/solid_cache/entry.rb
- lib/solid_cache/store/api.rb
- lib/solid_cache/store/entries.rb
- test/unit/solid_cache_test.rb
Add support for the unless_exist option to the write method. This will not overwrite the value and return false if the key already exists in the cache and is not expired.
Fixes: https://github.com/rails/solid_cache/issues/183
> Support unless_exist

- README.md
The current README command only add the migrations, not the config files.
But, two lines later in the same file, the docs reference `Configuration will be read from config/solid_cache.yml` - but, that file doesn't exist according to the current installation instructions. 
~~I think this approach is cleaner, especially so that changes in `defaults` on version upgrades don't cause weird issues in the future~~.
**Update:** I refactored to match the docs style of the `solid_queue` docs, which defaults to the full installation by default but explains a more manual approach.
> Docs: Run full installation by default (not just migrations)

- app/models/solid_cache/entry.rb
- lib/solid_cache/store/entries.rb
Use the new `dirties: false` option to `uncached` to disable the query cache and avoid the messy workarounds.
Currently only available in Rails edge so this will need to wait for its release. Will be part of Solid Cache v1.0, which will drop support for Rails 7.1 and earlier.
> Disable the query cache without workarounds

- README.md
- lib/generators/solid_cache/install/templates/config/solid_cache.yml.tt
- test/lib/generators/solid_cache/solid_cache/install_generator_test.rb
1. Use the DATABASE environment variable to match the name used in the installer
2. Default to "cache" which will match what Rails generators will use
> Correct config database

- app/models/solid_cache/entry.rb
I saw the release of 1.0.0 and noticed the code for reading queries from the database.
I found it a curious approach (took a while to figure out what the `gsub` did) and decide to have a try at making it more readable and in the end I also had some fun benchmarking the query and made it about 50% faster!
---
Here's my benchmark script:
```rb
require 'benchmark/ips'
require_relative "./test/test_helper"
Benchmark.ips do |x|
x.report("Entry.read") { SolidCache::Entry.read('bla') }
x.report("Entry.read_multi") { SolidCache::Entry.read_multi(['bla', 'blabla']) }
end
```
And here are some of my results, ran on a 2021 MBP M1 Pro.
With SQLite:
| What | Entry.read (i/s) | % | Entry.read_multi (i/s) | % |
| ---- | ---------------- | - | ---------------------- | - |
| **Current implementation** | …
> Improve performance of reading cache entries

- Rakefile
- lib/solid_cache/engine.rb
Support was added in https://github.com/rails/rails/pull/52729, so we can remove the check for Rails 8.
> Support binary encryption on PostgreSQL for Rails 8

- README.md
- lib/solid_cache/store/failsafe.rb
- test/unit/behaviors/failure_raising_behavior.rb
- test/unit/behaviors_rails_7_2/failure_raising_behavior.rb
- test/unit/execution_test.rb
- test/unit/solid_cache_test.rb
Avoid rescuing all ActiveRecord errors in the failsafe block as we might be hiding configuration errors.
Fixes: https://github.com/rails/solid_cache/issues/182
> Only failsafe on transient database errors

- lib/solid_cache/engine.rb
Ensure we load active_record before solid_cache - cc @dhh
> Require active_record in engine.rb

- lib/generators/solid_cache/install/templates/db/cache_schema.rb
Doesnt really matter but keeps consistency with the gemspec constraint. 
cc @dhh
> Update schema version to match gemspec

- lib/solid_cache/configuration.rb
- test/models/solid_cache/record_test.rb
- test/test_helper.rb
- test/unit/expiry_test.rb
When a database is specified, we should always manage connections so that we can ensure the cache is writable.
But if you just use the default connection for the rest of the app, we won't attempt to manage that.
Fixes: https://github.com/rails/solid_cache/issues/214
> Always manage connections when database is specified

- README.md
Minor README change. There are five options (not three) that can be set on the engine.
> Update readme - five options (not three) that can be set on the engine

- README.md
Formatting: Fix Markdown link formatting
Docs: Add acronym expansion for LRU (least recently used), to match how FIFO is expanded earlier in the same sentence
> Docs: Fix Markdown formatting, add LRU acronym expansion

- lib/solid_cache/store/expiry.rb
`concurrent/atomic/atomic_fixnum` was added by 2708b78a945eeb8874b1a57bf36c6f66320ee2bc. But, `Concurrent::AtomicFixnum` removed by b7b14b7.
> Remove unused require

- lib/solid_cache/store/failsafe.rb
It hides the error and you end up with a different error anyway as the connection is nil.
Fixes: https://github.com/rails/solid_cache/issues/235
> Don't failsafe ActiveRecord::ConnectionTimeoutError

- app/models/solid_cache/entry.rb
- test/models/solid_cache/entry_test.rb
To avoid massive multi read or write queries, we'll upsert and select in batches of 1000 keys.
> Batch multi queries
